name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, ci-cd ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verificar sintaxe do projeto
        run: python -m py_compile calculadora.py

      - name: Executar calculadora
        run: python calculadora.py
